#!/bin/bash

echo "Removing old backup directory..."
rm -rf /home/danila/cian_project/database_backup

echo "Creating a new backup directory..."
mkdir -p /home/danila/cian_project/database_backup

echo "Copying database from Docker container..."
sudo /usr/local/bin/copy_cian_database.sh
sleep 300

# Set ownership and permissions for the backup directory
echo "Setting permissions for the backup directory..."
sudo /usr/local/bin/cian_db_backup.sh

echo "Starting transfer..."
cd /home/danila/cian_project/cian_project2
if [ -z "$VIRTUAL_ENV" ]; then
    if [ -d "venv" ]; then
        echo "Activating virtual environment..."
        . venv/bin/activate
    else
        echo "Virtual environment not found. Exiting restart script."
        exit 1
    fi
else
    echo "Already in a virtual environment."
fi

echo "Running Python script to transfer the database to Yandex Disk..."
python3 -m py.transfer_db_to_yadisk

echo "Transfer completed."
